

function dZ = vertical_ascent(~,Z)
    
    global CRAFT PLANET ATMOSPHERE
        T  = CRAFT(1);
        II = CRAFT(2);
        IF = CRAFT(3);
        G  = PLANET(1);
        R  = PLANET(2);
        RS = PLANET(3);
        S  = PLANET(4);
        D  = ATMOSPHERE(1);
        H  = ATMOSPHERE(3);

    dZ = [Z(3); Z(4); ((-S/norm([Z(1),Z(2)])^3*[Z(1),Z(2)])+(-D*exp(-(...
        norm([Z(1),Z(2)])-R)/H)*norm([Z(3)-cos(atan2(Z(2),Z(1))-pi/2)*...
        RS, Z(4)-sin(atan2(Z(2),Z(1))-pi/2)*RS])*[Z(3)-cos(atan2(Z(2),...
        Z(1))-pi/2)*RS, Z(4)-sin(atan2(Z(2),Z(1))-pi/2)*RS])+(T/Z(5)*[...
        cos(atan2(Z(2),Z(1))), sin(atan2(Z(2),Z(1)))]))*[1;0]; ((-S/...
        norm([Z(1),Z(2)])^3*[Z(1),Z(2)])+(-D*exp(-(norm([Z(1),Z(2)])-R...
        )/H)*norm([Z(3)-cos(atan2(Z(2),Z(1))-pi/2)*RS, Z(4)-sin(atan2(...
        Z(2),Z(1))-pi/2)*RS])*[Z(3)-cos(atan2(Z(2),Z(1))-pi/2)*RS,...
        Z(4)-sin(atan2(Z(2),Z(1))-pi/2)*RS])+(T/Z(5)*[cos(atan2(Z(2),...
        Z(1))), sin(atan2(Z(2),Z(1)))]))*[0;1]; T/(((IF-II)*exp(-...
        (norm([Z(1),Z(2)])-R)/H)-IF)*G)];

end